# -*- coding: utf-8 -*-
"""edge_detection_preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UonjDWusJ7MQefW-RZCtaEqTQMD1f10Q
"""

from pathlib import Path
import pandas as pd
import numpy as np

from skimage.io import imread
from skimage.color import rgb2gray
from skimage.feature import canny
from skimage.filters import sobel
from skimage.transform import resize

DATA_ROOT = Path("dataset_will_go_here")

# file list
img_ext = {".jpg", ".jpeg"}
rows = [(p, p.parent.name) for p in DATA_ROOT.rglob("*") if p.suffix.lower() in img_ext]
df = pd.DataFrame(rows, columns=["path", "label"])
print(df["label"].value_counts())

# arbitrary number of entries for quick analysis
df_s = df.sample(min(2000, len(df)), random_state=42).reset_index(drop=True)

def compute_edge_metrics(path, size=(256, 256)):  # preprocessing
    img = imread(path)                            # load RGB
    gray = rgb2gray(img)                          # convert to grayscale float
    gray = resize(gray, size, anti_aliasing=True) # normalize image sizes for comparison

    edges = canny(gray, sigma=1.0)                # boolean edge map
    edge_density = float(edges.mean())            # % of pixels that are edges

    grad = sobel(gray)                            # gradient magnitude image
    mean_grad = float(grad.mean())
    std_grad = float(grad.std())

    return edge_density, mean_grad, std_grad

out = []
for path, label in zip(df_s["path"], df_s["label"]):
    ed, mg, sg = compute_edge_metrics(path)
    out.append({"path": str(path), "label": label,
                "edge_density": ed, "mean_grad": mg, "std_grad": sg})

metrics = pd.DataFrame(out)

summary = metrics.groupby("label").agg(
    n=("path", "count"),
    edge_density_mean=("edge_density", "mean"),
    edge_density_std=("edge_density", "std"),
    mean_grad_mean=("mean_grad", "mean"),
    mean_grad_std=("mean_grad", "std"),
).reset_index()

metrics.to_csv("edge_metrics_sample.csv", index=False)
summary.to_csv("edge_metrics_summary.csv", index=False)

summary